### PR TITLE
Fix issuses 15

### LINKED ISSUE #15: crash at `deinit {  ...   videoDataQueue.async { [weak self] in  ... }`
I push or present a new controller with QRScannerView(). when I pop or dismiss it , the QRScannerView.swift crash at line 137.
It seems that we can't use [weak self] at deinit method.

### PR DESCRIPTION
**Pull request by hitsubunnu**
resolve #15 

## Overflow

* It is possible that this object was over-released, or is in the process of deallocation.
スクリーンショット 2020-05-20 14 27 07

### CODE REVIEW

File: QRScanner/QRScannerView.swift [hunk 1]
```diff
@@ -133,11 +133,6 @@ public class QRScannerView: UIView {
         session.inputs.forEach { session.removeInput($0) }
         session.outputs.forEach { session.removeOutput($0) }
         removePreviewLayer()
-        if session.isRunning {
-            videoDataQueue.async { [weak self] in
-                self?.session.stopRunning()
```
Comment (daichiro) [inline QRScanner/QRScannerView.swift:138]: This is good to avoid crash but I wonder session will stop.
Please let me check 🙏

Comment (hitsubunnu) [reply QRScanner/QRScannerView.swift:138]: @daichiro FYI: I created a test branch to reappearance this issues. https://github.com/mercari/QRScanner/tree/issues_15_test

Comment (daichiro) [reply QRScanner/QRScannerView.swift:138]: @hitsubunnu Thanks! Your branch is really helpful!!
I confirmed `AVCaptureSession`'s `deinit` is called correctly.
